// Writes config.local.js from Netlify environment variables at build time.
// IMPORTANT: FIREBASE_API_KEY, FIREBASE_APP_ID, STRIPE_PRICE_ID must NOT be
// Netlify "secret" vars — secrets are masked (****************) in build output.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const out = path.join(root, 'config.local.js');

const firebase = {
  enabled: !!process.env.FIREBASE_API_KEY,
  apiKey: process.env.FIREBASE_API_KEY || '',
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || '',
  projectId: process.env.FIREBASE_PROJECT_ID || '',
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET || '',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || '',
  appId: process.env.FIREBASE_APP_ID || '',
};

const stripe = {
  enabled: !!process.env.STRIPE_PRICE_ID,
  priceId: process.env.STRIPE_PRICE_ID || '',
  proPriceLabel: process.env.STRIPE_PRO_PRICE_LABEL || '$0.99/mo',
};

const content = `// Auto-generated by scripts/netlify-config.js — do not edit on Netlify
const CONFIG_LOCAL = ${JSON.stringify({ firebase, stripe }, null, 2)};
`;

fs.writeFileSync(out, content, 'utf8');
console.log('Wrote config.local.js for Netlify build (firebase:', firebase.enabled, 'stripe:', stripe.enabled, ')');