# PlatePlanr — Firebase project setup (Auth + Firestore + Web + iOS apps)
# Uses Firebase agent skills workflow via firebase-tools CLI.
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
Set-Location $root

$env:PATH = "C:\Program Files\Git\cmd;C:\Program Files\nodejs;$env:APPDATA\npm;" + $env:PATH
$fb = "C:\Program Files\nodejs\npx.cmd"
$project = 'plateplanr-17793'
$bundleId = 'com.pluginrides.plateplanr'
$webName = 'plateplanr-web'
$netlify = "$env:APPDATA\npm\netlify.cmd"

function Invoke-Fb {
  param([string[]]$Args)
  & $fb -y firebase-tools@latest @Args
  if ($LASTEXITCODE -ne 0) { throw "firebase $($Args -join ' ') failed" }
}

Write-Host "`n=== PlatePlanr Firebase Setup ===`n" -ForegroundColor Green
Write-Host "Project: $project (number 154688205764)`n" -ForegroundColor Cyan

Write-Host "Step 1: Firebase login (browser may open)..." -ForegroundColor Yellow
& $fb -y firebase-tools@latest login:list 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
  & $fb -y firebase-tools@latest login
}

Invoke-Fb @('use', $project)

Write-Host "`nStep 2: List existing apps..." -ForegroundColor Yellow
$appsJson = & $fb -y firebase-tools@latest apps:list --project $project --json 2>$null
$apps = $appsJson | ConvertFrom-Json

$webApp = $apps.result | Where-Object { $_.platform -eq 'WEB' } | Select-Object -First 1
$iosApp = $apps.result | Where-Object { $_.platform -eq 'IOS' } | Select-Object -First 1
$knownIosId = '1:154688205764:ios:efc2244400a5bd25012a91'
if (-not $iosApp) {
  $iosApp = $apps.result | Where-Object { $_.appId -eq $knownIosId } | Select-Object -First 1
}

if (-not $webApp) {
  Write-Host "Creating Web app: $webName" -ForegroundColor Cyan
  $createWeb = & $fb -y firebase-tools@latest apps:create WEB $webName --project $project --json 2>$null | ConvertFrom-Json
  $webApp = $createWeb.result
} else {
  Write-Host "Web app exists: $($webApp.displayName) ($($webApp.appId))" -ForegroundColor Green
}

if (-not $iosApp) {
  Write-Host "Creating iOS (Apple) app: $bundleId" -ForegroundColor Cyan
  $createIos = & $fb -y firebase-tools@latest apps:create IOS $bundleId --project $project --json 2>$null | ConvertFrom-Json
  $iosApp = $createIos.result
} else {
  Write-Host "iOS app exists: $($iosApp.displayName) ($($iosApp.appId))" -ForegroundColor Green
}

Write-Host "`nStep 3: Fetch SDK configs..." -ForegroundColor Yellow
$webSdk = & $fb -y firebase-tools@latest apps:sdkconfig WEB $($webApp.appId) --project $project 2>$null
$iosPlist = & $fb -y firebase-tools@latest apps:sdkconfig IOS $($iosApp.appId) --project $project 2>$null

New-Item -ItemType Directory -Force -Path ios | Out-Null
$iosPlist | Set-Content -Path ios\GoogleService-Info.plist -Encoding utf8
$webSdk | Set-Content -Path firebase\web-sdk-config.txt -Encoding utf8

# Parse firebaseConfig from SDK output
$configBlock = ($webSdk -join "`n") -replace '(?s).*firebaseConfig\s*=\s*', '' -replace ';\s*$', ''
$cfg = $configBlock | ConvertFrom-Json

Write-Host "`nStep 4: Deploy Auth + Firestore rules..." -ForegroundColor Yellow
Invoke-Fb @('deploy', '--only', 'auth,firestore:rules', '--project', $project)

Write-Host "`nStep 5: Write config.local.js for local dev..." -ForegroundColor Yellow
$localJs = @"
// Auto-generated by scripts/setup-firebase.ps1 — Firebase Web SDK config
const CONFIG_LOCAL = {
  firebase: {
    enabled: true,
    apiKey: '$($cfg.apiKey)',
    authDomain: '$($cfg.authDomain)',
    projectId: '$($cfg.projectId)',
    storageBucket: '$($cfg.storageBucket)',
    messagingSenderId: '$($cfg.messagingSenderId)',
    appId: '$($cfg.appId)',
  },
  stripe: { enabled: false, priceId: '' },
};
"@
$localJs | Set-Content -Path config.local.js -Encoding utf8

Write-Host "`nStep 6: Set Netlify production env vars..." -ForegroundColor Yellow
if (Test-Path $netlify) {
  & $netlify env:set FIREBASE_API_KEY $cfg.apiKey --secret --context production --force | Out-Null
  & $netlify env:set FIREBASE_AUTH_DOMAIN $cfg.authDomain --context production --force | Out-Null
  & $netlify env:set FIREBASE_PROJECT_ID $cfg.projectId --context production --force | Out-Null
  & $netlify env:set FIREBASE_STORAGE_BUCKET $cfg.storageBucket --context production --force | Out-Null
  & $netlify env:set FIREBASE_MESSAGING_SENDER_ID $cfg.messagingSenderId --context production --force | Out-Null
  & $netlify env:set FIREBASE_APP_ID $cfg.appId --secret --context production --force | Out-Null
  Write-Host "Netlify Firebase vars set. Add FIREBASE_SERVICE_ACCOUNT separately if not set." -ForegroundColor Green
}

Write-Host @"

Done!
  Web app ID:    $($webApp.appId)
  iOS bundle ID: $bundleId
  iOS plist:     ios/GoogleService-Info.plist
  Local config:  config.local.js

Redeploy Netlify: netlify deploy --prod --skip-functions-cache --context production
"@ -ForegroundColor Green